### ISSUE TITLE
About WAITING4LPA

### ISSUE THREAD

**Issue by ScaMar** [SUSE/SAPHanaSR#43]
I'd like to share a behaviour i found while "joking" with a test cluster SLES15SP1 4SAP Application.

nodea and nodeb are running fine.

The hook wrote its properties into CIB:
`property SAPHanaSR: \
        hana_ph1_site_srHook_nodea=PRIM \
        hana_ph1_site_srHook_nodeb=SOK`

On nodeb i've shotdown pacemaker 
`systemctl stop pacemaker`
The hook modified its properties:
`property SAPHanaSR: \
        hana_ph1_site_srHook_nodea=PRIM \
        hana_ph1_site_srHook_nodeb=SFAIL`
Hana is still Active.

Let's suppose nodeb is broken and can't be put online.
A maintenance operation on nodea needs a restart.

After the restart, the cluster do not put online Hana instance.
The command SAPHanaSR-showAttr reports that nodea is in status `WAITING4LPA`

Is this the correct behaviour? If this happens on a Production system, are we forced to (temporarely) disable the SAPHanaSR hook in order to restart the hana instance within the cluster?

**Comment by fmherschel** [comment]
Is this a planned or running productive environment? Then please contact your linux vendor support organization. Here as a community chat I could only guess with the data you have shared.

If you have only ONE node back after the cluster was down with both (means ALL) nodes then the cluster MUST decline to start SAP HANA automatically. That's even defined in the man pages. The reason is that the cluster must never trust the only local CIB. It could not know, if the other node was primary in the meantime.
Only if both nodes are up they have synched their CIB-data and then we could be sure which cluster node was the newer primary in the past.
So the decline to start SAP HANA is a point of data integrity!

To solve your situation you do not need to disable the Hook. And I would you MUST NOT do that.

The solution would be to take the multi-state resource to maintenance. Start the SAP HANA DB primary, IF YOU ARE 150% ( :-) sure that this is the correct primary manually and then take the resource out of the maintenance mode. The cluster will then accept the new status defined by a human being.

And a secondary should never be down for a longer period of time as this would let the file systems being running full on the primary (all logs need to be kept for shipping). So your procedure is a double-error which should be that likely in a real life scenario.

If a secondary would be offline for a longer time this needs also to stop SR in my point of view. This also needs the cluster not to control that SAP HANA for that period of time.

**Comment by ScaMar** [comment]
@fmherschel thank you for reply
i confirm you this is a test environment (there was a copy/paste error in my message).
On this environment, i try every not ordinary event may happen that popup in my mind, in order to be sure how to react it.
So in case this happen in a production system (node must be offline to receive support) according to your reply, i see two scenarios:
Few hours offline:
1) Put the ms resource in maintenance 
2) handly manage hana (or use the cluster after the analysis)

Few days offline:
1) Stop the cluster
2) Disable the replica
3) Manage hana (and the VIP), handly until the second node is fixed

Once both nodes are online the cluster can be put online (not directly but following best practices books.

P.S.: About the man pages you mentioned, are those lines the once you referred?
`An important task of the resource agent is to check the synchronisation status
of the two SAP HANA databases. If the synchronisation is not "SOK", then the
cluster avoids to takeover to the secondary side, if the primary fails. This is
to improve the data consistency.`
So the takeover in my simulation ends Ok because replica status is SOK. Once i restart the cluster, hana went online because replica status was SFAIL. The cluster do not trust itself about last primary when he has no quorum, so someone must manage this no quorum / one node situation.

My expection is to never face this situation in a production environment :)
