### ISSUE TITLE
Run "SAPHanaSR-showAttr " Show score = -INFINITY

### ISSUE THREAD

**Issue by ZhangRei** [SUSE/SAPHanaSR#47]
I run SAPHanaSR-showAttr command and the slave node have iusse :
it show that "
Hosts    clone_state  lpa_hdp_lpt node_state op_mode              remoteHost roles                             score     site     srmode sync_state version                vhost    
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
NODE1 PROMOTED     1619661320  online     logreplay_readaccess omsapdb2   4:P:default:master1:master:worker 150       SiteA    sync   PRIM       2.00.036.00.1547699771 NODE1 
NODE2 WAITING4PRIM 30          online     logreplay            omsapdb1   4:S:master1:master:worker:master  -INFINITY NODE2 sync   SOK        2.00.036.00.1547699771 omsapdb2 
"
I notice that the node2(slave node) score = infinity 
I want to know what problem happened .
And what should i do to resovle it.

Best Regards

**Comment by fmherschel** [comment]
Which version of SAPHanaSR* are you using? I remember that we have had a problem where the clone status was pending in "WAITING4PRIM". Your output indeed looks a bit strange, because the lpa is already set to 30 and the SAP HANA roles indicates a started SAP HANA instance (4:S:...).
Maybe a "crm resource refresh <multi-state-resource>" could help by sending probes to all cluster nodes. Please also read our provided man pages.

**Comment by fmherschel** [comment]
@ZhangRei Still an open issue?

**Comment by fmherschel** [comment]
Sorry did wanted to close the issue.

**Comment by fmherschel** [comment]
Closing issue as we did not received any information after asking for SAPHanaSR version.
